### ISSUE TITLE
FUSE ipns mount is randomly buggy

### ISSUE THREAD

**Issue by rschulman** [ipfs/go-ipfs#1522]
The FUSE mount, at least when using OSXFUSE is not reliably useful. As an example, see this gist: https://gist.github.com/rschulman/3ce8c45cb68a6dfd844c

In here we can see that a directory listing shows no files/directories, but trying to make a directory reports that one is already there and indeed we can cd into it.

We can echo lines into a new file, but editing the file in vim and adding a line there results in an empty file.

I have also seen a result where copying a directory structure into ipns results in the directories being created correctly, but empty of files. In these cases files in the root directory are usually created but are empty.

Happy to try other things to try to find a root cause.

**Comment by whyrusleeping** [comment]
@rschulman I've had this exact same issue before a few times, and i thought i had fixed it. Although, the last time I fixed it, I dont think that I had a machine with OSX.

**Comment by jbenet** [comment]
wow, that's lovely. super broken lovely. @whyrusleeping can you help @rschulman debug this?

**Comment by whyrusleeping** [comment]
@jbenet last night i tried and failed to reproduce to this on OSX yosemite. I was running latest master, the entire ipns test suite passed (which i didnt actually expect) and i was able to do a large amount of routine filesystem actions on the mountpoint. @rschulman could you update to latest master, try again, and maybe provide some more insight on getting things to break?

**Comment by rschulman** [comment]
I updated to latest master but am still seeing the same behavior.

My OSX version is 10.10.4 and my OSX FUSE version is 27.

**Comment by whyrusleeping** [comment]
closing for now as vague. Fuse definitely needs work and that is well documented in other issues.
