### ISSUE TITLE
Mac ipfs daemon --mount and OSXFUSE

### ISSUE THREAD

**Issue by jamescarlyle** [ipfs/go-ipfs#1634]
Hi

I'm having problems mounting /ipfs - I've installed ipfs and OSXFUSE (2.8.0, via a .dmg package), but get the following error. 

Jamess-MacBook:~ jamescarlyle$ ipfs version
ipfs version 0.3.8-dev

Jamess-MacBook:~ jamescarlyle$ ipfs daemon --mount
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.16.51.60/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8081
Error: config key invalid: DontCheckOSXFUSE %!s(bool=true)
You may be able to get this error to go away by setting it again:

	ipfs config DontCheckOSXFUSE true

The current .ipfs/config file has the following line
  "DontCheckOSXFUSE": true,
This looks valid to me - i.e. the Error looks invalid.

Happy to try anything else, reinstall etc., keen to hear if anyone else can repeat this error.

James

**Comment by whyrusleeping** [comment]
@jamescarlyle try setting the config line to be `"true"` (a string). and see if that works.

**Comment by jamescarlyle** [comment]
Many thanks - that worked - but then the config is not being parsed as JSON, counter to this  statement "ipfs is configured through a json formatted text file, located by default at ~/.ipfs/config."

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#JavaScript_Object_Notation

So (strictly speaking) this issue is not resolved. I should fix and PR but have never used Go.  But IPFS looks awesome so maybe now is the time to learn.

**Comment by whyrusleeping** [comment]
@jamescarlyle it is being parsed as json, our code is apparently just expecting a string for some reason.

**Comment by jbenet** [comment]
yeah the code needs to change to expect a bool. though now, it should allow both to avoid breaking userspace:

```go
var res bool
switch v := v.(type) {
case string: 
  res = strings.LowerCase(v) == "true"
case bool: 
  res = v
}
```
or something.

**Comment by edrex** [comment]
this needs fixed. the default path of following the instructions provided on `ipfs mount` leads to `ipfs mount` being broken.

**Comment by csawyerYumaed** [comment]
ipfs version 0.4.2
I had to edit the config file by hand, this is the only way it worked for me.
 grep DontCheckOSXFUSE ~/.ipfs/config
  "DontCheckOSXFUSE": "true",

**Comment by whyrusleeping** [comment]
@csawyerYumaed this should be fixed in #3098. With that patch you should be able to use the command specified in the helptext

**Comment by chevdor** [comment]
Hello, just to confirm:
- ipfs version 0.4.2
- osxfuse installed using homebrew
Same issue than above, editing the config manually to replace true by "true" did the trick.

**Comment by csawyerYumaed** [comment]
@chevdor , it supposedly has been fixed, but the new version with this fix in place, has not yet been released, in fact, it doesn't look like it made it in time to get out on the 0.4.3 release (it's in release candidate 2), so probably it won't get fixed until they release 0.4.4, which sucks for all OSX users.

**Comment by chevdor** [comment]
that´s ok, this is no deal breaker and the documentation of the error makes it quite easy to land here and find a solution :)

**Comment by hmeine** [comment]
Still not working with official 0.4.4.

**Comment by TroyWilson1** [comment]
ipfs --version
0.4.13
OSX Fusion Version
OSXFUSE.FuseVersion: 29
OSXFUSE.AgentVersion: 3.7.1

After setting the config to "DontCheckOSXFUSE": "true", 
I just receive "Error: exit status 1"
Still Not working. Any ideas?
