### ISSUE TITLE
unexpected EOF in .tar.gz file from get command

### ISSUE THREAD

**Issue by amstocker** [ipfs/go-ipfs#1791]
I just tried to get a large file from ipfs using the get command using both the archive and compress options:

```bash
$ ipfs get --archive --compress QmTKZgRNwDNZwHtJSjCp6r5FYefzpULfy37JvMt9DwvXse
Saving archive to QmTKZgRNwDNZwHtJSjCp6r5FYefzpULfy37JvMt9DwvXse.tar.gz
43.04 MB 3s                                   
```

However when I try to unarchive it I get the following error:

```bash
$ tar -xzvf QmTKZgRNwDNZwHtJSjCp6r5FYefzpULfy37JvMt9DwvXse.tar.gz 
QmTKZgRNwDNZwHtJSjCp6r5FYefzpULfy37JvMt9DwvXse
QmTKZgRNwDNZwHtJSjCp6r5FYefzpULfy37JvMt9DwvXse/poster.jpg
QmTKZgRNwDNZwHtJSjCp6r5FYefzpULfy37JvMt9DwvXse/video.mp4
QmTKZgRNwDNZwHtJSjCp6r5FYefzpULfy37JvMt9DwvXse/video.webm

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Also when trying to use python's tarfile capabilities I also get errors that look like: `IOError: CRC check failed 0x3b94367b != 0x1a9b23adL`, if that is any help.

**Comment by amstocker** [comment]
I just tried the same thing without `--compress` and I'm still getting the same error.

**Comment by rht** [comment]
Which version are you using? Should have been fixed in master since https://github.com/ipfs/go-ipfs/commit/23dd82f5490edaf4a1685e1a2227f764d29e700c

**Comment by amstocker** [comment]
Ah ok, I'm using `ipfs version 0.3.8-dev`.

**Comment by amstocker** [comment]
Ok it is all fine now, thanks.

**Comment by robcat** [comment]
@rht @amstocker
I'm using  0.3.11-dev and I'm still getting errors.
For example: QmSXfUAh4HfMNgBcDisZ7tbA4cRMXzuJ3BdrjAz1T5TTjw
(it's [this file](http://mirror.23media.de/archlinux/extra/os/x86_64/gtk3-3.18.6-1-x86_64.pkg.tar.xz), decompressed with xz and added with `ipfs tar add`)

**Comment by whyrusleeping** [comment]
This is an issue of documentation. Right now, the `ipfs tar add` command creates objects that can only be easily used by the `ipfs tar cat` command. 

Further integration of `ipfs tar` created objects into the other commands is *definitely* planned, Its just taking a bit of thought to figure out how best to do it in a way that doesnt privelege one format unnecessarily. (thats not to say `ipfs tar` doesnt already privelege the tar format, but thats the sort of thing we want to avoid whenever we can)

**Comment by robcat** [comment]
> This is an issue of documentation. Right now, the ipfs tar add command creates objects that can only be easily used by the ipfs tar cat command.

I see two possible ways to go:

Option 1: **Transparent archives**
- `ipfs tar add <archive.tar>` is the equivalent of `tar xf <archive.tar>; ipfs add -r <archive>` (but it doesn't write on disk the decompressed archive)
- `ipfs tar cat <multihash>` is the equivalent of `ipfs get <hash>; tar cf <hash.tar> <hash>` (but it doesn't write on disk the decompressed archive)
- `ipfs get <archive.tar>` would be completely unaware of the existence of tar archives, and save a simple directory

In this case `ipfs tar` would *not* influence any other part of ipfs project: it would just be a quick way to import/export files without writing the uncompressed archive on disk.

Option 2: **Smart Chunking**
- `ipfs tar add` detects the file boundaries in the tar file and applies a sort of pre-chunking (i.e. file headers are standalone chunks, and any other chunk can contain data from only one file)
- `ipfs tar cat` does not exist
- `ipfs get` would be completely unaware of the existence of tar archives and happily download the archive as a normal file (at most, it will notice an odd chunking)

Using option 1 discards by default some header content (owner, permissions, xattrs, etc.), but they could be *optionally* added as a special node in the dag and smartly restored by tar cat.

@whyrusleeping What do you think?

**Comment by sbuss** [comment]
I'm not sure if this has been resolved, in part, by any other tickets, so forgive me if my comment isn't relevant.

I think Option 2 will result in a better user experience, but I'd extend it to filetype plugins that do it automatically for a small subset of base filetypes. So `ipfs add foo.tar` detects the file is a tar file, runs the smart chunking, and only syncs the blocks the network hasn't seen. Then `ipfs get $hash` writes out a tar file but with efficient block trading. However, I understand that filetype-specific behavior is not necessarily ideologically aligned with IPFS and `ipfs add --filetype=tar foo.tar` might be better (or the current `tar add` approach).

My use case for this is something like:

```sh
docker save -o ubuntu.tar ubuntu
docker save -o foobuntu.tar foobuntu  # shares docker layers with the ubuntu image
ipfs add ubuntu.tar
ipfs add foobuntu.tar  # detects the majority of the data is already in ipfs and only syncs the new docker FS layers
```
